services:
  sogo:
    image: sogo
    ports:
      - "${PORT_SOGO_HTTP:-8080}:80"
    volumes:
      - ./sogo-conf:/etc/sogo:ro
      - ./nginx-conf/sites-enabled:/etc/nginx/sites-enabled:ro
      - ./backup:/mnt/backup
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: password

  # Uncomment to allow access to the database administrator interface
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8088:8080
