version: "2.1"
services:
  sogo:
    image: japoch/docker-sogo-raspbian:latest
    ports:
      - "8080:80"
    volumes:
      - ./sogo-conf:/etc/sogo:ro
      - ./nginx-root:/var/www
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: linuxserver/mariadb:10.6.12
    ports:
      - "3306:3306"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=sogo
      - MYSQL_USER=sogo
      - MYSQL_PASSWORD=password
    volumes:
      - ./db-root:/config
    restart: unless-stopped

  phpmyadmin:
    image: linuxserver/phpmyadmin:5.2.1
    ports:
      - "8081:80"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PMA_ARBITRARY=1
    volumes:
      - ./phpmyadmin-root:/config
    restart: unless-stopped
    depends_on:
      - db
